[general]
name = "langarena"
version = "0.1.0"

[build]
files = [
    "main.fix",
    "helper.fix",
    "bench.fix",
    "benchmarks/binarytrees.fix",
    "benchmarks/brainfuck.fix",
    "benchmarks/buffer_hash.fix",
    "benchmarks/compress_bwt.fix",
    "benchmarks/fannkuchredux.fix",
    "benchmarks/game_of_life.fix",
    "benchmarks/jaro.fix",
    "benchmarks/mandelbrot.fix",
    "benchmarks/matmul.fix",
    "benchmarks/nbody.fix",
    "benchmarks/sieve.fix",
    "benchmarks/sort.fix",
    "benchmarks/spectralnorm.fix",
]

[[dependencies]]
name = "time"
version = "2.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-time.git" }

[[dependencies]]
name = "minilib-json"
version = "0.7.0"
git = { url = "https://github.com/pt9999/fixlang-minilib-json.git" }

[[dependencies]]
name = "minilib-collection"
version = "0.9.0"
git = { url = "https://github.com/pt9999/fixlang-minilib-collection.git" }


[[dependencies]]
name = "math"
version = "2.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-math.git" }