#!/bin/bash

../xtime.rb php -d opcache.enable=1 \
    -d opcache.enable_cli=1 \
    -d opcache.jit=tracing \
    -d opcache.jit_buffer_size=256M \
    -d memory_limit=-1 \
    main.php ../run.js "$@"
